force-app/main/default/objects/Scheduled_Request__c/Scheduled_Request__c.object-meta.xml
<CustomObject>
    <label>Scheduled Request</label>
    <nameField>
        <label>Scheduled Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scheduled Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Scheduled_Request__c/fields/Domain__c.field-meta.xml
<CustomField>
    <fullName>Domain__c</fullName>
    <label>Domain</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Application_Domain</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Scheduled_Request__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Scheduled_Request__c/fields/Payload__c.field-meta.xml
<CustomField>
    <fullName>Payload__c</fullName>
    <label>Payload</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Scheduled_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OppgaveRetry_Batch.cls
public with sharing class OppgaveRetry_Batch implements Database.Batchable<SObject>, Database.AllowsCallouts {
    private String query;

    public OppgaveRetry_Batch() {
        this.query = 'SELECT Id, Method__c, Status__c, Payload__c, CreatedDate FROM Scheduled_Request__c WHERE Status__c = \'Scheduled\' and Domain__c = \'NKS\'';
    }
    public OppgaveRetry_Batch(String query) {
        this.query = query;
    }

    public Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext BC, List<SObject> scope) {
        List<Scheduled_Request__c> oppgaveRequestList = (List<Scheduled_Request__c>) scope;
        LoggerUtility logger = new LoggerUtility('OppgaveRetry_Batch');
        try {
            OppgaveRetry.retryScheduledRequest(oppgaveRequestList);
        } catch (Exception ex) {
            logger.exception(ex, null, CRM_ApplicationDomain.Domain.NKS);
        }
        logger.publish();
    }

    public void finish(Database.BatchableContext BC) {
        // No post-processing needed after batch completes
    }
}